name: Caching restore

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Restore cached Primes
      id: cache-file
      uses: actions/cache@v4
      with:
        path: prime-numbers
        key: ${{ runner.os }}-primes

    - name: Echo Cache Hit
      run: echo ${{ steps.cache-file.outputs.cache-hit }}
      
    - name: Generate Prime Numbers
      run: cat prime-numbers/primes.txt