name: Caching

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: generate files
      run: |
        mkdir -p prime-numbers
        echo "Generating prime numbers"
        for i in {1..100}; do
          echo $i >> prime-numbers/primes.txt
        done
    - name: Cache file
      id: cache-file
      uses: actions/cache@v4
      with:
        path: prime-numbers
        key: ${{ runner.os }}-primes

    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: cat prime-numbers/primes.txt

    - name: Use Prime Numbers
      run: cat prime-numbers/primes.txt