name: Caching

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Restore cached
      id: restore-cache
      uses: actions/cache/save@v4
      with:
        path: cache-dir
        key: ${{ runner.os }}-cache
    - name: generate cache files
      if : steps.restore-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p cache-dir
        echo "Generating cache file..."
        sleep 60
        for i in {1..100}; do
          echo $i >> cache-dir/cache.txt
        done
   

    - name: Use Prime Numbers
      run: cat cache-dir/cache.txt
    
    - name: Cache generated file
      if : steps.restore-cache.outputs.cache-hit != 'true'
      id: cache-file
      uses: actions/cache/save@v4
      with:
        path: cache-dir
        key: ${{ runner.os }}-cache