name: Service container
on: workflow_dispatch
jobs:
  
  runner-job:
    runs-on: ubuntu-latest
    services:
      web-service:
        image: hung6876/my-image:45226cb
        ports:
          - 80:80
    steps:
      - name: curl_web_service
        run: curl http://localhost:80