name: Echo Variables
on: push
jobs:
  
  runner-job:
    runs-on: ubuntu-latest
    steps:
    
        
      - uses: actions/checkout@v4
        with:
          sparse-checkout: test_checkout
          sparse-checkout-cone-mode: true
      - name: List Dirs
        run: |
          echo "Listing all files..."
          ls
