name: Test checkout
on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  
  runner-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Git Log
        run: |
          git log
      - name: List all file
        run: ls ** -a
